### PR TITLE
Update to v2.3.2

### PR DESCRIPTION
**Pull request by KingDarBoja**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by KingDarBoja** [comment]
@conda-forge-admin, please rerender

**Comment by bollwyvl** [comment]
@KingDarBoja thanks for the ping. I didn't the upstream was still putting out 2.x releases. We'll have to make a long-running branch for this... will do so, and update the PR to target it. We may have to add your name to `master`, as well...

**Comment by KingDarBoja** [comment]
@bollwyvl Thanks for the quick response.

Just to inform you, `graphql-python` is striving towards moving all related packages to use `graphql-core v3` instead of `v2` but as transition will be slower for already existing apps, we just releasing small fixes and telling everyone to use latest version instead.

In order to do that, we are releasing a final v2 version for these packages and making the switch with newest version of graphql-core to follow semantic versioning.

**Comment by bollwyvl** [comment]
Ran into some weird-looking conflicts. Started a new PR (#20) with your changes, rather than try to back out the various things here. Feel free to reply wherever you prefer, should get this sorted presently...

**Pull request closed without merging**
